services:
    db:
        image: mongo:latest
        container_name: mongodb
        ports:
            - "27017:27017"
        # environment:
        #     - MONGO_INITDB_ROOT_USERNAME=admin
        #     - MONGO_INITDB_ROOT_PASSWORD=password
        env_file:
            - ./apps/server/.env
        volumes:
            - mongo_data:/data/db

    server:
        build:
            context: .
            dockerfile: apps/server/Dockerfile
        container_name: server
        ports:
            - "8000:8000"
        # environment:
        #     - PORT=8000
        #     - MONGODB_URI=mongodb://admin:password@db:27017/campusForum?authSource=admin
        #     - REFRESH_TOKEN=your_refresh_token_secret
        #     - REFRESH_TOKEN_EXP=7d
        #     - ACCESS_TOKEN=your_access_token_secret
        #     - ACCESS_TOKEN_EXP=1d
        env_file:
            - ./apps/server/.env
        depends_on:
            - db

    client:
        build:
            context: .
            dockerfile: apps/client/Dockerfile
        container_name: client
        ports:
            - "5173:5173"
        environment:
            - VITE_API_TARGET=http://server:8000
        depends_on:
            - server

volumes:
    mongo_data:
